Repository MLH-Fellowship/project-reboot-rebels, pull requests merged in 2022-06, with the labels that each got.

#10 Home
  app/__init__.py
  app/static/img/logo.jpg
  app/static/img/logo.svg
  app/templates/index.html
Labels: minor patch

#12 Timeline
  app/__init__.py
  app/data.py
  app/static/img/Headshot_Roa.png
  app/static/img/hobbies.png
  app/static/img/pro.png
  app/static/styles/timeline.css
  app/templates/base.html
  app/templates/timeline.html
Labels: enhancement, Task

#18 Fixed merge Added Makefile and data compatability
  .gitignore
  LICENSE.md
  README.md
  app/__init__.py
  app/data.py
  app/static/styles/about.css
  app/static/styles/index.css
  app/static/styles/main.css
  app/static/styles/timeline.css
  app/templates/about.html
  app/templates/base.html
  app/templates/index.html
  app/templates/timeline.html
  makefile
  requirements.txt
Labels: enhancement
